# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/production/gateway"
    schedule:
      interval: "weekly"
      day: "saturday"
    commit-message:
      prefix: "chore: gateway"
  - package-ecosystem: "npm"
    directory: "/production/types"
    schedule:
      interval: "weekly"
      day: "saturday"
    commit-message:
      prefix: "chore: types"
  - package-ecosystem: "npm"
    directory: "/production/example"
    schedule:
      interval: "weekly"
      day: "saturday"
    commit-message:
      prefix: "chore: example"
