version: "3"
services:
  registry:
    image: registry:2
    hostname: registry
    restart: always
    ports:
      - "5000:5000"
    environment:
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /data
    volumes:
      - ./local-registry:/data
      - ./config/htpasswd:/auth/htpasswd